services:
  backend-api:
    # THE UPGRADE: We no longer build from source. We pull the frozen image from GitHub!
    image: ghcr.io/gmnguegnang/rag-app-scientific-qa-backend:latest
    network_mode: "host"
    environment:
      - OLLAMA_URL=http://localhost:11434/api/generate

  frontend-ui:
    # Pull the frozen UI image
    image: ghcr.io/gmnguegnang/rag-app-scientific-qa-frontend:latest
    network_mode: "host"
    environment:
      - BACKEND_API_URL=http://localhost:8080/api/chat
    depends_on:
      - backend-api